name: "Unit Tests"

on:
  push:
    branches:
      - master
      - branch/*
  pull_request:
    branches:
      - master
      - branch/*

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-22.04-32core
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Run tests
      run: |
        make test
